In [31]:
mms = MinMaxScaler()
type(MinMaxScaler())
type(mms)
isinstance(mms, MinMaxScaler)

sklearn.preprocessing._data.MinMaxScaler

sklearn.preprocessing._data.MinMaxScaler

True

<IPython.core.display.Javascript object>

In [57]:
import inspect


def f(mms=MinMaxScaler()):
    kk = MinMaxScaler()
    print(type(mms))
    print(type(MinMaxScaler()))
    print(type(kk))
    print(isinstance(MinMaxScaler(), MinMaxScaler))
    print(isinstance(mms, MinMaxScaler))
    print(isinstance(kk, MinMaxScaler))
    print(inspect.isclass(mms))
    print(inspect.isclass(kk))
    print(inspect.isclass(MinMaxScaler))

<IPython.core.display.Javascript object>

In [24]:
ind = np.arange(5)
ind
list(range(5))
np.array(range(5))

array([0, 1, 2, 3, 4])

[0, 1, 2, 3, 4]

array([0, 1, 2, 3, 4])

<IPython.core.display.Javascript object>

In [13]:
ind_mask = np.ones(5, dtype=np.bool)
ind_mask
ind_mask_2 = np.ones(5, dtype=np.bool, order="F")
ind_mask_2

array([ True,  True,  True,  True,  True])

array([ True,  True,  True,  True,  True])

<IPython.core.display.Javascript object>

In [15]:
ind_mask[[2, 3]] = False
~ind_mask

array([False, False,  True,  True, False])

<IPython.core.display.Javascript object>

In [ ]:
np.sort(np.array(test_index))
np.array_equal(
    np.array(train_index), list(PredefinedHoldoutSplit(train_index).split(X, y))[0][1]
)

In [19]:
ind[ind_mask]
ind[~ind_mask]

array([0, 1, 4])

array([2, 3])

<IPython.core.display.Javascript object>

In [23]:
# Return elements chosen from x or y depending on `condition`
np.where(ind_mask, False, True)

array([False, False,  True,  True, False])

<IPython.core.display.Javascript object>

In [1]:
# Preferences of autoformatting & Multiple Output
%load_ext nb_black

from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all"

import warnings

warnings.filterwarnings("ignore")

import researchpy as rp  # For auto-statistics/EDA of dataframe
from tqdm.notebook import tqdm  # For process display
import pingouin as pg

import sys

sys.path.append("../src")

from data import *
from utils import *
from conf import *
from tools import *

import utils as UT
import tools as TS

import random

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go

from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import Pipeline, make_pipeline, FeatureUnion

from sklearn import set_config

set_config(display="diagram")

pd.set_option("display.max_colwidth", 200)

<IPython.core.display.Javascript object>

In [2]:
!ls "../output/"
df_child = pd.read_excel("../output/CHILD_with_addon.xlsx", index_col="Subject_Number")
df_child_backup = df_child.copy()

5y_Modelling.xlsx                   CHILD_with_addon.xlsx
CHILD_ml_sample_dataset.xlsx        targeted_raw_child.xlsx
CHILD_raw.xlsx                      unprocessed_targeted_raw_child.xlsx


<IPython.core.display.Javascript object>